In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df= df.join(pd.get_dummies(df['Gender']))

In [5]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased  Female  Male
0  15624510    Male   19            19000          0       0     1
1  15810944    Male   35            20000          0       0     1
2  15668575  Female   26            43000          0       1     0
3  15603246  Female   27            57000          0       1     0
4  15804002    Male   19            76000          0       0     1

In [7]:
X = df.iloc[:,[2,3,5,6]].values
y = df.iloc[:,4].values

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=5)

In [16]:
X_train

array([[    46,  23000,      0,      1],
       [    28,  44000,      1,      0],
       [    51,  23000,      0,      1],
       ...,
       [    28,  32000,      0,      1],
       [    55, 130000,      1,      0],
       [    60,  34000,      0,      1]], dtype=int64)

In [18]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [19]:
X_train

array([[ 0.77063564, -1.37090753, -1.03390789,  1.03390789],
       [-0.95681661, -0.74731782,  0.96720415, -0.96720415],
       [ 1.25048349, -1.37090753, -1.03390789,  1.03390789],
       ...,
       [-0.95681661, -1.1036548 , -1.03390789,  1.03390789],
       [ 1.63436177,  1.8064305 ,  0.96720415, -0.96720415],
       [ 2.11420962, -1.0442653 , -1.03390789,  1.03390789]])

In [20]:
from sklearn.svm import SVC

In [21]:
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [22]:
y_pred = classifier.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [25]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[59,  7],
       [ 9, 25]], dtype=int64)

In [26]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.84

In [34]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)

In [35]:
grid_search.best_score_

0.9066666666666666

In [36]:
grid_search.best_params_

{'C': 1, 'gamma': 0.7, 'kernel': 'rbf'}

In [39]:
classifier = SVC(C=1, gamma= 0.7, kernel= 'rbf')

In [40]:
classifier.fit(X_train,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.7, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.93